# .github/workflows/nox.yaml
# Copyright 2023 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

permissions: {}

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  schedule: [{ cron: "15 0 * * *" }]
  workflow_dispatch:
    inputs:
      repository-url:
        type: choice
        description: Upload API endpoint for PyPI
        options:
          # https://github.com/pypa/gh-action-pypi-publish/blob/unstable/v1/action.yml#L23
          - https://upload.pypi.org/legacy/
          - https://test.pypi.org/legacy/
        default: https://upload.pypi.org/legacy/

jobs:
  nox:
    runs-on: ubuntu-latest
    outputs: { version: "${{ steps.version.outputs.version }}" }
    steps:
      - run: sudo apt-get update && sudo apt-get --yes install meson
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with: { persist-credentials: false }
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with: { python-version: "3.13" }
      - run: ./noxfile.py
      - id: version
        shell: python
        run: |
          #!/usr/bin/env python3
          """Write the version number to GITHUB_OUTPUT."""

          from os import environ
          from pathlib import Path

          START = '__version__ = "'
          END = '"'
          OUTPUT = Path(environ.get("GITHUB_OUTPUT", "github_output.txt"))


          for line in Path("reproducibly.py").read_text().splitlines():
              if line.startswith(START) and line.endswith(END):
                  break
          else:
              msg = "Line not found."
              raise ValueError(msg)

          msg = "version=" + line.removeprefix(START).removesuffix(END) + "\n"
          OUTPUT.write_text(msg)

      - name: Upload dist/ for the publish job and to debug unexpected changes
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with: { name: dist, path: dist }
        if: always()
      - name: Upload wheelhouse/ to debug unexpected changes
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with: { name: wheelhouse, path: wheelhouse }
        if: always()
      - uses: dprint/check@9cb3a2b17a8e606d37aae341e49df3654933fc23 # v2.3
  zizmor:
    runs-on: ubuntu-24.04
    # https://github.com/zizmorcore/zizmor-action#permissions
    permissions: { security-events: write }
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with: { persist-credentials: false }
      # yamllint disable-line rule:line-length
      - uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
  publish:
    needs: [nox, zizmor]
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'workflow_dispatch' }}"
    permissions: { id-token: write }
    environment:
      name: pypi
      url: >-
        https://${{
          contains(github.event.inputs.repository-url, 'test') && 'test.' || ''
        }}pypi.org/project/reproducibly/${{
          needs.nox.outputs.version
        }}/
    steps:
      - name: Prevent deployments outside test from outside main
        run: "false"
        if: >-
          ${{ !( github.ref == 'refs/heads/main'
          || contains(github.event.inputs.repository-url, 'test')) }}
        # yamllint disable-line rule:line-length
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with: { name: dist, path: dist }
      - run: cd dist && sha256sum -c SHA256SUMS && rm SHA256SUMS
        # yamllint disable-line rule:line-length
      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          print-hash: true
          packages-dir: dist
          repository-url: ${{ github.event.inputs.repository-url }}
